CCF_NAMESPACE='https://hubmapconsortium.github.io/hubmap-ontology/ccf.owl'

CCF_PARTONOMY_TERMS='source_data/ccf-term-list.csv'
CCF_MODEL='docs/ccf-model.owl'
CCF_PARTONOMY_RDF='docs/ccf-partonomy.rdf'
CCF_CONTEXT='source_data/ccf-context.jsonld'
CCF_REFERENCE_ENTITIES='source_data/reference-spatial-entities.jsonld'
CCF_REFERENCE_ENTITIES_RDF='docs/ccf-reference-entities.rdf'
HUBMAP_ENTITIES='source_data/hubmap-spatial-entities.jsonld'
HUBMAP_ENTITIES_RDF='docs/hubmap-spatial-entities.rdf'
CCF_FULL_ONTOLOGY='docs/ccf.owl'
