# CCF_NAMESPACE='https://hubmapconsortium.github.io/hubmap-ontology/ccf.owl'
CCF_NAMESPACE='http://purl.org/ccf/latest/ccf.owl'

CCF_PARTONOMY_TERMS='source_data/ccf-term-list.csv'
CCF_MODEL='dist/ccf-model.owl'
CCF_PARTONOMY_RDF='dist/ccf-partonomy.rdf'
CCF_PARTONOMY_JSONLD='dist/ccf-partonomy.jsonld'
CCF_PARTONOMY_CSV='dist/ccf-partonomy.csv'
CCF_CONTEXT='source_data/ccf-context.jsonld'
CCF_REFERENCE_ENTITIES='source_data/reference-spatial-entities.jsonld'
CCF_GENERATED_REFERENCE_ENTITIES='source_data/generated-reference-spatial-entities.jsonld'
CCF_REFERENCE_ENTITIES_RDF='dist/ccf-reference-entities.rdf'
CCF_FULL_ONTOLOGY='dist/ccf.owl'
