owl_filename: slim.ttl
owl_filetype: turtle
ccf_input_filename: input_data/ccf_input_terms.csv
cell_type_input_filename: input_data/cell_type_input_terms.csv
ignore_terms: input_data/ignore.csv
dot_files:
    entire_ontology: True
    root_nodes: True
    non_leaf_nodes: True
ontologies:
    UBERON_filename: input_data/ext.owl
    CL_filename: cl.owl
partonomy:
    path: ../ontologies/partonomy/
    filename_base: partonomy
    filename_suffix: .owl
    filetype: pretty-xml
    json_suffix: .jsonld
    json_type: json-ld
    
